openapi: 3.2.0
info:
  title: HighBond API Reference Entities API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Entities
  description: 'Entities may be business units, departments, locations, or key initiatives that are within the scope of the organization. Entities have a hierarchical structure composed of parent and child entities. Once you have set up your organization''s nested entity structure, you can tag different items with entities.


    Learn more about entities.'
paths:
  /orgs/{org_id}/entities:
    get:
      tags:
      - Entities
      operationId: getEntities
      summary: Get entities
      description: Get all entities.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/entitySparseFieldsetParams'
      - $ref: '#/components/parameters/pageSizeParam'
      - $ref: '#/components/parameters/pageNumberEncodedParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetEntitiesResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - Entities
      operationId: createEntity
      summary: Create an entity
      description: 'Create an new entity.


        Limitations:

        * There can be a maximum of 5000 entities per HighBond instance.

        * Entity titles can be a maximum of 120 characters long.

        * If you provide a parent relationship, none of the children can refer to any of their ancestors (parent, parent of parent, etc.).'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/entitySparseFieldsetParams'
      requestBody:
        description: The data required to create an entity.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateEntityRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetEntityResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/title
                  code: invalid_resource
                  detail: is too long (maximum is 120 characters)
  /orgs/{org_id}/entities/{id}:
    get:
      tags:
      - Entities
      operationId: getEntity
      summary: Get an entity
      description: Get information about an entity.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/entitySparseFieldsetParams'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetEntityResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    patch:
      tags:
      - Entities
      operationId: updateEntity
      summary: Update an entity
      description: 'Make changes to an entity in account, like renaming the entity title or updating the entity description.


        Limitations:

        * Entity titles can be a maximum of 120 characters long.

        * If you provide a parent relationship, none of the children can refer to any of their ancestors (parent, parent of parent, etc.).'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/entitySparseFieldsetParams'
      requestBody:
        description: The data required to update an entity.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateEntityRequest'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetEntityResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/title
                  code: invalid_resource
                  detail: is too long (maximum is 120 characters)
    delete:
      tags:
      - Entities
      operationId: deleteEntity
      summary: Delete an entity
      description: 'Permanently delete an entity from a project.


        > **Caution —**

        Deleting an entity is permanent. Once deleted, you cannot access or restore the entity.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
  /orgs/{org_id}/entity_categories:
    get:
      tags:
      - Entities
      operationId: getEntityCategories
      summary: Get a list of entity categories
      description: Get information about entity categories.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/entityCategorySparseFieldsetParams'
      - $ref: '#/components/parameters/pageSizeParam'
      - $ref: '#/components/parameters/pageNumberEncodedParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetEntityCategoriesResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - Entities
      operationId: createEntityCategory
      summary: Create an entity category
      description: 'Create a new entity category.


        Limitations:

        * There can be a maximum of 500 entity categories per HighBond instance.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/entityCategorySparseFieldsetParams'
      requestBody:
        description: The data required to create an entity category.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateEntityCategoryRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CreateEntityCategoryResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/weight
                  code: invalid_resource
                  detail: must be less than or equal to 100
  /orgs/{org_id}/entity_categories/{id}:
    get:
      tags:
      - Entities
      operationId: getEntityCategory
      summary: Get an entity category
      description: Get information about an entity category.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/entityCategorySparseFieldsetParams'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetEntityCategoryResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    patch:
      tags:
      - Entities
      operationId: updateEntityCategory
      summary: Update an entity category
      description: Make changes to entity category.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/entityCategorySparseFieldsetParams'
      requestBody:
        description: The data required to update an entity category.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateEntityCategoryRequest'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetEntityCategoryResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/weight
                  code: invalid_resource
                  detail: must be less than or equal to 100
    delete:
      tags:
      - Entities
      operationId: deleteEntityCategory
      summary: Delete an entity category
      description: 'Permanently delete an entity category.


        Once an Entity Category is deleted via API, its relationship to all Entities is removed as well. No Entities are deleted as a result of this action.


        > **Caution —**

        Deleting an Entity Category is permanent. Once deleted, you cannot access or restore the Entity Category.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
components:
  parameters:
    entityCategorySparseFieldsetParams:
      in: query
      name: fields[entity_categories]
      description: Requesting the API to return only the specified fields. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: title,description,position,entities_count,created_at,updated_at,entities
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    entitySparseFieldsetParams:
      in: query
      name: fields[entities]
      description: Requesting the API to return only the specified fields. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: title,description,created_at,updated_at,parent,children_count,entity_category
    pageSizeParam:
      in: query
      name: page[size]
      description: The number of items returned per page. Default is 50. Maximum is 100.
      required: false
      schema:
        type: string
        example: 25
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    pageNumberEncodedParam:
      in: query
      name: page[number]
      description: The Base64-encoded page number of records to return.
      required: false
      schema:
        type: string
        example: Mg==
  schemas:
    CreateEntityCategoryRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          - relationships
          properties:
            type:
              type: string
              description: The type of entity category (`"entity_categories"`).
              example: entity_categories
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - title
              properties:
                title:
                  type: string
                  description: the name of entity category
                  maxLength: 60
                  example: My new entity category
                description:
                  type: string
                  description: the description of entity category
                  example: My new description
    CreateEntityCategoryResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The type of entity category (`"entity_categories"`).
              example: entity_categories
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - title
              properties:
                title:
                  type: string
                  description: the name of entity category
                  maxLength: 60
                  example: My new entity category
                description:
                  type: string
                  description: the description of entity category
                  example: My new description
                position:
                  type: integer
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
                entities_count:
                  type: integer
                  description: 'Related entities count, is a value between `1` and `2147483647`.

                    '
                  example: 1
                created_at:
                  type: string
                  description: The timestamp identifying when the entity category was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the entity category was last updated.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
    CreateEntityRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The type of resource (`"entities"`).
              example: entities
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - title
              properties:
                title:
                  type: string
                  description: The title of the entity.
                  maxLength: 120
                  example: Entity title
                description:
                  type: string
                  description: A detailed description of the entity.
                  maxLength: 524288
                  example: Entity description
            relationships:
              type: object
              description: The relationships associated with the resource.
              properties:
                entity_category:
                  type:
                  - object
                  - 'null'
                  description: 'Each entity can be associated to the category.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the category.
                          example: '54'
                        type:
                          type: string
                          description: The classification of the object (`"entity_categories"`).
                          example: entity_categories
                parent:
                  type:
                  - object
                  - 'null'
                  description: 'Each entity can be associated to the parent entity.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the entity.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"entities"`).
                          example: entities
                children:
                  type:
                  - object
                  - 'null'
                  description: 'Each entity can have multiple associated entities.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        description: 'Entity associated with a parent entity.


                          >**Note**: only existing top-level entities can be assigned as children

                          '
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the entity.
                            example: '3'
                          type:
                            type: string
                            description: The classification of the object (`"entities"`).
                            example: entities
    GetEntityResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '2'
            type:
              type: string
              description: The type of resource (`"entities"`).
              example: entities
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - title
              properties:
                title:
                  type: string
                  description: The title of the entity.
                  maxLength: 120
                  example: Entity title
                description:
                  type: string
                  description: A detailed description of the entity.
                  maxLength: 524288
                  example: Entity description
                children_count:
                  type: integer
                  description: A count of entity children.
                  example: 1
                created_at:
                  type: string
                  description: The timestamp identifying when the entity was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the entity was last updated.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
            relationships:
              type: object
              description: The relationships associated with the resource.
              properties:
                entity_category:
                  type:
                  - object
                  - 'null'
                  description: 'Each entity can be associated to the category.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the category.
                          example: '54'
                        type:
                          type: string
                          description: The classification of the object (`"entity_categories"`).
                          example: entity_categories
                parent:
                  type:
                  - object
                  - 'null'
                  description: 'Each entity can be associated to the parent entity.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the entity.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"entities"`).
                          example: entities
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    GetEntityCategoryResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The type of entity category (`"entity_categories"`).
              example: entity_categories
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - title
              properties:
                title:
                  type: string
                  description: the name of entity category
                  maxLength: 60
                  example: My new entity category
                description:
                  type: string
                  description: the description of entity category
                  example: My new description
                position:
                  type: integer
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
                entities_count:
                  type: integer
                  description: 'Related entities count, is a value between `1` and `2147483647`.

                    '
                  example: 1
                created_at:
                  type: string
                  description: The timestamp identifying when the entity category was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the entity category was last updated.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
            relationships:
              type: object
              description: The relationships associated with the resource.
              properties:
                entities:
                  type: object
                  description: 'Each entity category may have associated entities.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        description: Entities associated with a category
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the entity.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"entities"`).
                            example: entities
    UpdateEntityCategoryRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The type of entity category (`"entity_categories"`).
              example: entity_categories
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                title:
                  type: string
                  description: the name of entity category
                  maxLength: 60
                  example: My new entity category
                description:
                  type: string
                  description: the description of entity category
                  example: My new description
                position:
                  type: integer
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
    UpdateEntityRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '2'
            type:
              type: string
              description: The type of resource (`"entities"`).
              example: entities
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - title
              properties:
                title:
                  type: string
                  description: The title of the entity.
                  maxLength: 120
                  example: Entity title
                description:
                  type: string
                  description: A detailed description of the entity.
                  maxLength: 524288
                  example: Entity description
            relationships:
              type: object
              description: The relationships associated with the resource.
              properties:
                entity_category:
                  type:
                  - object
                  - 'null'
                  description: 'Each entity can be associated to the category.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the category.
                          example: '54'
                        type:
                          type: string
                          description: The classification of the object (`"entity_categories"`).
                          example: entity_categories
                parent:
                  type:
                  - object
                  - 'null'
                  description: 'Each entity can be associated to the parent entity.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the entity.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"entities"`).
                          example: entities
                children:
                  type:
                  - object
                  - 'null'
                  description: 'Each entity can have multiple associated entities.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        description: 'Entity associated with a parent entity.


                          >**Note**: only existing top-level entities can be assigned as children

                          '
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the entity.
                            example: '3'
                          type:
                            type: string
                            description: The classification of the object (`"entities"`).
                            example: entities
    GetEntityCategoriesResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: array
          description: The data associated with the resource.
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            - relationships
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '1'
              type:
                type: string
                description: The type of entity category (`"entity_categories"`).
                example: entity_categories
              attributes:
                type: object
                description: The attributes associated with the resource.
                required:
                - title
                properties:
                  title:
                    type: string
                    description: the name of entity category
                    maxLength: 60
                    example: My new entity category
                  description:
                    type: string
                    description: the description of entity category
                    example: My new description
                  position:
                    type: integer
                    description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                      '
                    example: 1
                  entities_count:
                    type: integer
                    description: 'Related entities count, is a value between `1` and `2147483647`.

                      '
                    example: 1
                  created_at:
                    type: string
                    description: The timestamp identifying when the entity category was created.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  updated_at:
                    type: string
                    description: The timestamp identifying when the entity category was last updated.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
              relationships:
                type: object
                description: The relationships associated with the resource.
                properties:
                  entities:
                    type: object
                    description: 'Each entity category may have associated entities.

                      '
                    required:
                    - data
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          description: Entities associated with a category
                          required:
                          - id
                          - type
                          properties:
                            id:
                              type: string
                              description: The ID of the entity.
                              example: '1'
                            type:
                              type: string
                              description: The classification of the object (`"entities"`).
                              example: entities
        links:
          type: object
          required:
          - next
          - prev
          properties:
            next:
              type:
              - string
              - 'null'
              description: Next page url
              example: /api/resource?page[number]=Mg==
            prev:
              type:
              - string
              - 'null'
              description: Previous page url
              example: null
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    GetEntitiesResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            - relationships
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '2'
              type:
                type: string
                description: The type of resource (`"entities"`).
                example: entities
              attributes:
                type: object
                description: The attributes associated with the resource.
                required:
                - title
                properties:
                  title:
                    type: string
                    description: The title of the entity.
                    maxLength: 120
                    example: Entity title
                  description:
                    type: string
                    description: A detailed description of the entity.
                    maxLength: 524288
                    example: Entity description
                  children_count:
                    type: integer
                    description: A count of entity children.
                    example: 1
                  created_at:
                    type: string
                    description: The timestamp identifying when the entity was created.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  updated_at:
                    type: string
                    description: The timestamp identifying when the entity was last updated.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
              relationships:
                type: object
                description: The relationships associated with the resource.
                properties:
                  entity_category:
                    type:
                    - object
                    - 'null'
                    description: 'Each entity can be associated to the category.

                      '
                    required:
                    - data
                    properties:
                      data:
                        type: object
                        description: The data associated with the resource.
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the category.
                            example: '54'
                          type:
                            type: string
                            description: The classification of the object (`"entity_categories"`).
                            example: entity_categories
                  parent:
                    type:
                    - object
                    - 'null'
                    description: 'Each entity can be associated to the parent entity.

                      '
                    required:
                    - data
                    properties:
                      data:
                        type: object
                        description: The data associated with the resource.
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the entity.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"entities"`).
                            example: entities
        links:
          type: object
          required:
          - next
          - prev
          properties:
            next:
              type:
              - string
              - 'null'
              description: Next page url
              example: /api/resource?page[number]=Mw==
            prev:
              type:
              - string
              - 'null'
              description: Previous page url
              example: null
  responses:
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
    NoContent:
      description: No content.
    ResourceTypeMismatch:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: resource_type_mismatch
              title: Resource type mismatch
              detail: 'The requested data type, a-bad-type, is incompatible with the endpoint.

                '
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
