openapi: 3.2.0
info:
  title: HighBond API Reference Frameworks API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Frameworks
  description: 'A framework is a management system that allows you to define objectives, risks, and controls, perform tests, and compile information for reporting purposes. Frameworks may also

    be known as audits, compliance assessments, risk assessments, or another customized term.


    Learn more about frameworks.'
paths:
  /orgs/{org_id}/frameworks:
    get:
      tags:
      - Frameworks
      operationId: getFrameworks
      summary: Get frameworks
      description: Get a list of all frameworks in an account.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/frameworkSparseFieldsetParams'
      - $ref: '#/components/parameters/pageSizeParam'
      - $ref: '#/components/parameters/pageNumberEncodedParam'
      - $ref: '#/components/parameters/filterName'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetFrameworksResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - Frameworks
      operationId: createFramework
      summary: Create a framework
      description: 'Create a new framework from scratch.


        Limitations:

        * There can be a maximum of 1000 frameworks per HighBond instance.

        * You cannot enable risk assurance (`risk_assurance: true`) when you first create a framework.

        However, you can enable risk assurance when you update a framework.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/frameworkSparseFieldsetParams'
      requestBody:
        description: The data required to create a framework.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateFrameworkRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetFrameworkResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/name
                  code: invalid_resource
                  detail: can't be blank
  /orgs/{org_id}/frameworks/{id}:
    get:
      tags:
      - Frameworks
      operationId: getFramework
      summary: Get a framework
      description: Get information about a framework.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/frameworkSparseFieldsetParams'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetFrameworkResponseWithIncludes'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    patch:
      tags:
      - Frameworks
      operationId: updateFramework
      summary: Update a framework
      description: Make changes to a framework.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/frameworkSparseFieldsetParams'
      requestBody:
        description: The data required to update a framework.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateFrameworkRequest'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetFrameworkResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/name
                  code: invalid_resource
                  detail: can't be blank
                - status: 422
                  source:
                    pointer: /data/attributes/entities
                  code: invalid_resource
                  detail: 'Missing child or parent entity ids: [1, 2 ,3]'
                - status: 422
                  source:
                    pointer: /data/attributes/entities
                  code: invalid_resource
                  detail: 'Missing inherited entity ids: [1, 2, 3]'
    delete:
      tags:
      - Frameworks
      operationId: deleteFramework
      summary: Delete a framework
      description: 'Delete a framework that you no longer require.


        > **Caution —**

        Once a framework is permanently deleted, you cannot access or restore the framework.


        For more information, see Deleting frameworks.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/state
                  code: invalid_resource
                  detail: Invalid framework state for the requested action.
  /orgs/{org_id}/frameworks/{framework_id}/entities:
    post:
      tags:
      - Frameworks
      operationId: createFrameworkEntityLink
      summary: Create framework entity link
      description: 'Link entity to a framework.


        > **Note**

        > * Tagging a framework to an entity automatically tags a framework with all ancestor entities and descendant entities.

        > * Request Get a framework with `entities` query param to get the whole list of entities linked to a framework.


        Limitations:

        * Only 1 entity can be sent in the request payload.


        Learn more about tagging items with entities.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/frameworkIdParam'
      requestBody:
        description: The data required to create a framework entity link.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateFrameworkEntityRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CreateFrameworkEntityResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/base
                  code: invalid_resource
                  detail: Entity and Responsibility should reference the same account.
  /orgs/{org_id}/frameworks/{framework_id}/entities/{id}:
    delete:
      tags:
      - Frameworks
      operationId: deleteFrameworkEntityLink
      summary: Delete framework entity link
      description: 'Permanently delete framework entity link.


        > **Note -**

        Untagging a framework from an entity automatically untags a framework from all descendant entities.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/frameworkIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
components:
  parameters:
    frameworkSparseFieldsetParams:
      in: query
      name: fields[frameworks]
      description: Requesting the API to return only the specified fields. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: name,created_at,updated_at,folder_name,description,background,position,purpose,scope,risk_assurance,entities,project_type,collaborators,risk_assurance_data,collaborator_groups
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    pageSizeParam:
      in: query
      name: page[size]
      description: The number of items returned per page. Default is 50. Maximum is 100.
      required: false
      schema:
        type: string
        example: 25
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    pageNumberEncodedParam:
      in: query
      name: page[number]
      description: The Base64-encoded page number of records to return.
      required: false
      schema:
        type: string
        example: Mg==
    frameworkIdParam:
      in: path
      name: framework_id
      description: The ID of the framework.
      required: true
      schema:
        type: integer
        example: 1
    filterName:
      in: query
      name: filter[name]
      description: Filter by name.  Response will include partial matches and ignore case.
      required: false
      schema:
        type: string
        example: LoremIpsum
  responses:
    Accepted:
      description: Accepted.
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
    NoContent:
      description: No content.
    ResourceTypeMismatch:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: resource_type_mismatch
              title: Resource type mismatch
              detail: 'The requested data type, a-bad-type, is incompatible with the endpoint.

                '
  schemas:
    GetFrameworksResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      - links
      properties:
        data:
          type: array
          description: Array of frameworks
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            - relationships
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '1'
              type:
                type: string
                description: The classification of the object (`"frameworks"`).
                example: frameworks
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  name:
                    type: string
                    description: The name of the framework.
                    maxLength: 120
                    example: Example Application
                  created_at:
                    type: string
                    description: The timestamp specifying when the framework was created.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  updated_at:
                    type: string
                    description: The timestamp specifying when the framework's settings were updated.
                    example: '2019-03-18T22:02:05Z'
                    format: date-time
                  folder_name:
                    type: string
                  description:
                    type: string
                    description: A detailed description of the framework.
                    maxLength: 524288
                    example: Framework description.
                  background:
                    type: string
                    description: The contextual circumstances of the framework.
                    maxLength: 524288
                    example: <h1>Heading</h1><p>Framework background description.</p>
                  purpose:
                    type: string
                    description: The intended results, aims, or goals of the framework.
                    maxLength: 524288
                    example: <h1>Heading</h1><p>Framework purpose description.</p>
                  scope:
                    type: string
                    description: What is, and is not, covered by this framework.
                    maxLength: 524288
                    example: <h1>Heading</h1><p>Framework scope description.</p>
                  position:
                    type: integer
                    format: int64
                    description: 'Legacy field that was used to determine the order in which it is displayed in the index action. This field is no longer supported and will always return 0.

                      '
                    example: 0
                  risk_assurance:
                    type: boolean
                    description: 'Specifies if the Risk Assurance feature has been enabled (`true`) or disabled (`false`) for the project. The default is `false`.

                      You must be a System Admin with a Professional subscription to configure this field. For more information, see

                      <a href="https://help.highbond.com/helpdocs/highbond/en-us/Content/projects/risk_assurance/getting_started_with_assurance_for_risk.html"

                      target="_blank">Getting started with assurance for risk</a>.

                      '
                    example: false
                  custom_attributes:
                    type: array
                    description: An array of custom attributes defined on the project type used by this framework. <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-project-types" target="_blank">Learn more about project types</a>. Make a PATCH request to modify the value of a custom attribute.
                    items:
                      type: object
                      description: A user defined custom attribute value.
                      properties:
                        id:
                          type: string
                          description: The ID of this custom attribute. Optional if term is included.
                          example: '42'
                        term:
                          type: string
                          description: The user defined term used to identify this custom attribute. Optional if id is included.
                          example: Custom Framework Planning Attribute
                        value:
                          type: array
                          description: The value or values (for multiselect) for this custom attribute.
                          example:
                          - Custom Select Option Text
                          items:
                            type: string
                  risk_assurance_data:
                    type: object
                    description: 'Fields that determines assurance values. Assurance is an expression of confidence that risk is effectively mitigated. Returns `null` if Risk Assurance feature is disabled.

                      '
                    properties:
                      inherent_risk:
                        type: number
                        format: float
                        description: 'The risk that an activity would pose if no controls or other mitigating factors were in place. Can also be referred to as the gross risk, or risks before controls, and can act as the baseline for your organization''s risk tolerance or appetite.

                          '
                        example: 1.1
                      residual_risk:
                        type: number
                        format: float
                        description: 'The risk that remains after controls are taken into account. Can also be referred to as the net risk or risk after controls.

                          '
                        example: 1.1
                      assurance:
                        type: number
                        description: 'The level of assurance that the controls in place effectively mitigate risk to the business.

                          '
                        example: 0
              relationships:
                type: object
                description: The relationships associated with the resource.
                required:
                - project_type
                properties:
                  project_type:
                    type:
                    - object
                    - 'null'
                    description: 'Each framework has an associated project type. Project types define the structure of a framework, including the terminology used in the framework.

                      The project type defines which workflow the framework uses and which custom attributes are available on the framework. Because of this dependency

                      the project type can''t be updated at the same time as the custom attributes.

                      '
                    required:
                    - data
                    properties:
                      data:
                        type: object
                        description: The data associated with the resource.
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the project type.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"project_types"`).
                            example: project_types
                  entities:
                    type: object
                    description: Each framework has an associated framework entities.
                    required:
                    - data
                    properties:
                      data:
                        type: array
                        description: The data associated with the resource.
                        items:
                          type: object
                          required:
                          - id
                          - type
                          properties:
                            id:
                              type: string
                              description: The ID of the entity.
                              example: '1'
                            type:
                              type: string
                              description: The classification of the object (`"entities"`).
                              example: entities
        links:
          type: object
          required:
          - next
          - prev
          properties:
            next:
              type:
              - string
              - 'null'
              description: Next page url
              example: /api/resource?page[number]=Mg==
            prev:
              type:
              - string
              - 'null'
              description: Previous page url
              example: null
    GetFrameworkResponseWithIncludes:
      type: object
      description: The data included in the response.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"frameworks"`).
              example: frameworks
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                name:
                  type: string
                  description: The name of the framework.
                  maxLength: 120
                  example: Example Application
                created_at:
                  type: string
                  description: The timestamp specifying when the framework was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp specifying when the framework's settings were updated.
                  example: '2019-03-18T22:02:05Z'
                  format: date-time
                folder_name:
                  type: string
                description:
                  type: string
                  description: A detailed description of the framework.
                  maxLength: 524288
                  example: Framework description.
                background:
                  type: string
                  description: The contextual circumstances of the framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework background description.</p>
                purpose:
                  type: string
                  description: The intended results, aims, or goals of the framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework purpose description.</p>
                scope:
                  type: string
                  description: What is, and is not, covered by this framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework scope description.</p>
                position:
                  type: integer
                  format: int64
                  description: 'Legacy field that was used to determine the order in which it is displayed in the index action. This field is no longer supported and will always return 0.

                    '
                  example: 0
                risk_assurance:
                  type: boolean
                  description: 'Specifies if the Risk Assurance feature has been enabled (`true`) or disabled (`false`) for the project. The default is `false`.

                    You must be a System Admin with a Professional subscription to configure this field. For more information, see

                    <a href="https://help.highbond.com/helpdocs/highbond/en-us/Content/projects/risk_assurance/getting_started_with_assurance_for_risk.html"

                    target="_blank">Getting started with assurance for risk</a>.

                    '
                  example: false
                custom_attributes:
                  type: array
                  description: An array of custom attributes defined on the project type used by this framework. <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-project-types" target="_blank">Learn more about project types</a>. Make a PATCH request to modify the value of a custom attribute.
                  items:
                    type: object
                    description: A user defined custom attribute value.
                    properties:
                      id:
                        type: string
                        description: The ID of this custom attribute. Optional if term is included.
                        example: '42'
                      term:
                        type: string
                        description: The user defined term used to identify this custom attribute. Optional if id is included.
                        example: Custom Framework Planning Attribute
                      value:
                        type: array
                        description: The value or values (for multiselect) for this custom attribute.
                        example:
                        - Custom Select Option Text
                        items:
                          type: string
                risk_assurance_data:
                  type: object
                  description: 'Fields that determines assurance values. Assurance is an expression of confidence that risk is effectively mitigated. Returns `null` if Risk Assurance feature is disabled.

                    '
                  properties:
                    inherent_risk:
                      type: number
                      format: float
                      description: 'The risk that an activity would pose if no controls or other mitigating factors were in place. Can also be referred to as the gross risk, or risks before controls, and can act as the baseline for your organization''s risk tolerance or appetite.

                        '
                      example: 1.1
                    residual_risk:
                      type: number
                      format: float
                      description: 'The risk that remains after controls are taken into account. Can also be referred to as the net risk or risk after controls.

                        '
                      example: 1.1
                    assurance:
                      type: number
                      description: 'The level of assurance that the controls in place effectively mitigate risk to the business.

                        '
                      example: 0
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - project_type
              properties:
                project_type:
                  type:
                  - object
                  - 'null'
                  description: 'Each framework has an associated project type. Project types define the structure of a framework, including the terminology used in the framework.

                    The project type defines which workflow the framework uses and which custom attributes are available on the framework. Because of this dependency

                    the project type can''t be updated at the same time as the custom attributes.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the project type.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"project_types"`).
                          example: project_types
                entities:
                  type: object
                  description: Each framework has an associated framework entities.
                  required:
                  - data
                  properties:
                    data:
                      type: array
                      description: The data associated with the resource.
                      items:
                        type: object
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the entity.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"entities"`).
                            example: entities
    CreateFrameworkEntityResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          properties:
            id:
              type: string
              description: The ID of the framework.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"entities"`).
              example: entities
    GetFrameworkResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"frameworks"`).
              example: frameworks
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                name:
                  type: string
                  description: The name of the framework.
                  maxLength: 120
                  example: Example Application
                created_at:
                  type: string
                  description: The timestamp specifying when the framework was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp specifying when the framework's settings were updated.
                  example: '2019-03-18T22:02:05Z'
                  format: date-time
                folder_name:
                  type: string
                description:
                  type: string
                  description: A detailed description of the framework.
                  maxLength: 524288
                  example: Framework description.
                background:
                  type: string
                  description: The contextual circumstances of the framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework background description.</p>
                purpose:
                  type: string
                  description: The intended results, aims, or goals of the framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework purpose description.</p>
                scope:
                  type: string
                  description: What is, and is not, covered by this framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework scope description.</p>
                position:
                  type: integer
                  format: int64
                  description: 'Legacy field that was used to determine the order in which it is displayed in the index action. This field is no longer supported and will always return 0.

                    '
                  example: 0
                risk_assurance:
                  type: boolean
                  description: 'Specifies if the Risk Assurance feature has been enabled (`true`) or disabled (`false`) for the project. The default is `false`.

                    You must be a System Admin with a Professional subscription to configure this field. For more information, see

                    <a href="https://help.highbond.com/helpdocs/highbond/en-us/Content/projects/risk_assurance/getting_started_with_assurance_for_risk.html"

                    target="_blank">Getting started with assurance for risk</a>.

                    '
                  example: false
                custom_attributes:
                  type: array
                  description: An array of custom attributes defined on the project type used by this framework. <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-project-types" target="_blank">Learn more about project types</a>. Make a PATCH request to modify the value of a custom attribute.
                  items:
                    type: object
                    description: A user defined custom attribute value.
                    properties:
                      id:
                        type: string
                        description: The ID of this custom attribute. Optional if term is included.
                        example: '42'
                      term:
                        type: string
                        description: The user defined term used to identify this custom attribute. Optional if id is included.
                        example: Custom Framework Planning Attribute
                      value:
                        type: array
                        description: The value or values (for multiselect) for this custom attribute.
                        example:
                        - Custom Select Option Text
                        items:
                          type: string
                risk_assurance_data:
                  type: object
                  description: 'Fields that determines assurance values. Assurance is an expression of confidence that risk is effectively mitigated. Returns `null` if Risk Assurance feature is disabled.

                    '
                  properties:
                    inherent_risk:
                      type: number
                      format: float
                      description: 'The risk that an activity would pose if no controls or other mitigating factors were in place. Can also be referred to as the gross risk, or risks before controls, and can act as the baseline for your organization''s risk tolerance or appetite.

                        '
                      example: 1.1
                    residual_risk:
                      type: number
                      format: float
                      description: 'The risk that remains after controls are taken into account. Can also be referred to as the net risk or risk after controls.

                        '
                      example: 1.1
                    assurance:
                      type: number
                      description: 'The level of assurance that the controls in place effectively mitigate risk to the business.

                        '
                      example: 0
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - project_type
              properties:
                project_type:
                  type:
                  - object
                  - 'null'
                  description: 'Each framework has an associated project type. Project types define the structure of a framework, including the terminology used in the framework.

                    The project type defines which workflow the framework uses and which custom attributes are available on the framework. Because of this dependency

                    the project type can''t be updated at the same time as the custom attributes.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the project type.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"project_types"`).
                          example: project_types
                entities:
                  type: object
                  description: Each framework has an associated framework entities.
                  required:
                  - data
                  properties:
                    data:
                      type: array
                      description: The data associated with the resource.
                      items:
                        type: object
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the entity.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"entities"`).
                            example: entities
    CreateFrameworkEntityRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          properties:
            id:
              type: string
              description: The ID of the framework.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"entities"`).
              example: entities
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    CreateFrameworkRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          - relationships
          properties:
            type:
              type: string
              description: The classification of the object (`"frameworks"`).
              example: frameworks
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - name
              - start_date
              - target_date
              properties:
                name:
                  type: string
                  description: The name of the framework.
                  maxLength: 120
                  example: Example Application
                description:
                  type: string
                  description: A detailed description of the framework.
                  maxLength: 524288
                  example: Framework description.
                background:
                  type: string
                  description: The contextual circumstances of the framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework background description.</p>
                purpose:
                  type: string
                  description: The intended results, aims, or goals of the framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework purpose description.</p>
                scope:
                  type: string
                  description: What is, and is not, covered by this framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework scope description.</p>
                folder_name:
                  type: string
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - project_type
              properties:
                project_type:
                  type:
                  - object
                  - 'null'
                  description: 'Each framework has an associated project type. Project types define the structure of a framework, including the terminology used in the framework.

                    The project type defines which workflow the framework uses and which custom attributes are available on the framework. Because of this dependency

                    the project type can''t be updated at the same time as the custom attributes.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the project type.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"project_types"`).
                          example: project_types
    UpdateFrameworkRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"frameworks"`).
              example: frameworks
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - name
              - start_date
              - target_date
              properties:
                name:
                  type: string
                  description: The name of the framework.
                  maxLength: 120
                  example: Example Application
                description:
                  type: string
                  description: A detailed description of the framework.
                  maxLength: 524288
                  example: Framework description.
                background:
                  type: string
                  description: The contextual circumstances of the framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework background description.</p>
                purpose:
                  type: string
                  description: The intended results, aims, or goals of the framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework purpose description.</p>
                scope:
                  type: string
                  description: What is, and is not, covered by this framework.
                  maxLength: 524288
                  example: <h1>Heading</h1><p>Framework scope description.</p>
                folder_name:
                  type: string
                risk_assurance:
                  type: boolean
                  description: 'Specifies if the Risk Assurance feature has been enabled (`true`) or disabled (`false`) for the project. The default is `false`.

                    You must be a System Admin with a Professional subscription to configure this field. For more information, see

                    <a href="https://help.highbond.com/helpdocs/highbond/en-us/Content/projects/risk_assurance/getting_started_with_assurance_for_risk.html"

                    target="_blank">Getting started with assurance for risk</a>.

                    '
                  example: false
                custom_attributes:
                  type: array
                  description: An array of custom attributes defined on the project type used by this framework. <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-project-types" target="_blank">Learn more about project types</a>. Make a PATCH request to modify the value of a custom attribute.
                  items:
                    type: object
                    description: A user defined custom attribute value.
                    properties:
                      id:
                        type: string
                        description: The ID of this custom attribute. Optional if term is included.
                        example: '42'
                      term:
                        type: string
                        description: The user defined term used to identify this custom attribute. Optional if id is included.
                        example: Custom Framework Planning Attribute
                      value:
                        type: array
                        description: The value or values (for multiselect) for this custom attribute.
                        example:
                        - Custom Select Option Text
                        items:
                          type: string
            relationships:
              type:
              - object
              - 'null'
              description: The relationships associated with the resource.
              properties:
                project_type:
                  type:
                  - object
                  - 'null'
                  description: 'Each framework has an associated project type. Project types define the structure of a framework, including the terminology used in the framework.

                    The project type defines which workflow the framework uses and which custom attributes are available on the framework. Because of this dependency

                    the project type can''t be updated at the same time as the custom attributes.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the project type.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"project_types"`).
                          example: project_types
                entities:
                  type: object
                  description: 'The passed entities list should match the following conditions:

                    1. It should be the full exact list of entities you would like to be linked to the resource.


                    2. The passed entities should consist of valid sub-trees with all ancestor entities as well as descendent entities.


                    3. Inherited entities should be included too.


                    Otherwise, the whole request will be rejected with the corresponding error.

                    '
                  properties:
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                            description: The ID of the entity.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"entities"`).
                            example: entities
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
