openapi: 3.2.0
info:
  title: HighBond API Reference Request item statuses API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Request item statuses
  description: 'Request statuses provide visibility into the progress of request resolutions. The number of available statuses, and the terms used for each status, can be customized by the organization.


    Learn more about request item statuses.'
paths:
  /orgs/{org_id}/project_types/{project_type_id}/request_item_statuses:
    get:
      tags:
      - Request item statuses
      operationId: getRequestItemStatuses
      summary: Get request item statuses
      description: Get a list of all request item statuses associated with a project type.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/projectTypeIdParam'
      - $ref: '#/components/parameters/requestItemStatusSparseFieldsetParams'
      - $ref: '#/components/parameters/pageSizeParam'
      - $ref: '#/components/parameters/pageNumberEncodedParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRequestItemStatusesResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - Request item statuses
      operationId: createRequestItemStatus
      summary: Create a request item status
      description: Create a new request item status in an existing project type.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/projectTypeIdParam'
      - $ref: '#/components/parameters/requestItemStatusSparseFieldsetParams'
      requestBody:
        description: The data required to create a request item status.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateRequestItemStatusRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRequestItemStatusResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/customizable_type
                  code: invalid_resource
                  detail: Must include customizable_type.
  /orgs/{org_id}/request_item_statuses/{id}:
    get:
      tags:
      - Request item statuses
      operationId: getRequestItemStatus
      summary: Get a request item status
      description: Get information about a request item status.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/requestItemStatusSparseFieldsetParams'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRequestItemStatusResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    patch:
      tags:
      - Request item statuses
      operationId: updateRequestItemStatus
      summary: Update a request item status
      description: Make changes to a request item status in a project type, like modifying the term or field_type.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/requestItemStatusSparseFieldsetParams'
      requestBody:
        description: The data required to update a request item status.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateRequestItemStatusRequest'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRequestItemStatusResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/customizable_type
                  code: invalid_resource
                  detail: Must include customizable_type.
    delete:
      tags:
      - Request item statuses
      operationId: deleteRequestItemStatus
      summary: Delete a request item status
      description: 'Permanently delete a request item status from a project type.

        > **Caution —**

        Deleting a request item status permanently removes the field and all associated data from all relevant projects and frameworks.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  code: UnprocessibleEntity
                  detail: Default request item status can't be deleted.
components:
  schemas:
    GetRequestItemStatusesResponse:
      type: object
      required:
      - data
      - links
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            - relationships
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '1'
              type:
                type: string
                description: The type of the request item status (`"request_item_statuses"`).
                example: request_item_statuses
              attributes:
                type: object
                description: The attributes associated with the resource.
                required:
                - status
                properties:
                  status:
                    type: string
                    description: The displayed name of the request item status.
                    example: Open
                  action:
                    type: string
                    description: 'The action of the request item status.

                      '
                    enum:
                    - nothing
                    - warning
                    example: warning
                  default:
                    type: boolean
                    description: 'Specifies if the request item status is default (`true`) or not (`false`). The default statuses can''t be deleted.

                      '
                    example: true
                  created_at:
                    type: string
                    description: The timestamp identifying when the narrative was created.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  updated_at:
                    type: string
                    description: The timestamp identifying when the narrative was last updated.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
              relationships:
                type: object
                description: The relationships associated with the resource.
                required:
                - project_type
                properties:
                  project_type:
                    type: object
                    description: 'Each request item status has an associated project type. Project types define the structure of a project or framework,

                      including the terminology used in the project or framework.

                      '
                    required:
                    - data
                    properties:
                      data:
                        type: object
                        description: The data associated with the resource.
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the project type that this request item status belongs to.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"project_types"`).
                            example: project_types
    GetRequestItemStatusResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The type of the request item status (`"request_item_statuses"`).
              example: request_item_statuses
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - status
              properties:
                status:
                  type: string
                  description: The displayed name of the request item status.
                  example: Open
                action:
                  type: string
                  description: 'The action of the request item status.

                    '
                  enum:
                  - nothing
                  - warning
                  example: warning
                default:
                  type: boolean
                  description: 'Specifies if the request item status is default (`true`) or not (`false`). The default statuses can''t be deleted.

                    '
                  example: true
                created_at:
                  type: string
                  description: The timestamp identifying when the narrative was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the narrative was last updated.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - project_type
              properties:
                project_type:
                  type: object
                  description: 'Each request item status has an associated project type. Project types define the structure of a project or framework,

                    including the terminology used in the project or framework.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the project type that this request item status belongs to.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"project_types"`).
                          example: project_types
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    CreateRequestItemStatusRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The type of the request item status (`"request_item_statuses"`).
              example: request_item_statuses
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - status
              - action
              properties:
                status:
                  type: string
                  description: The displayed name of the request item status.
                  example: Open
                action:
                  type: string
                  description: 'The action of the request item status.

                    '
                  enum:
                  - nothing
                  - warning
                  example: warning
    UpdateRequestItemStatusRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The type of the request item status (`"request_item_statuses"`).
              example: request_item_statuses
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - status
              properties:
                status:
                  type: string
                  description: The displayed name of the request item status.
                  example: Open
                action:
                  type: string
                  description: 'The action of the request item status.

                    '
                  enum:
                  - nothing
                  - warning
                  example: warning
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
  parameters:
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    pageSizeParam:
      in: query
      name: page[size]
      description: The number of items returned per page. Default is 50. Maximum is 100.
      required: false
      schema:
        type: string
        example: 25
    projectTypeIdParam:
      in: path
      name: project_type_id
      description: The ID of the project type.
      required: true
      schema:
        type: integer
        example: 1
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    requestItemStatusSparseFieldsetParams:
      in: query
      name: fields[request_item_statuses]
      description: Requesting the API to return only the specified fields. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: status,action,default
    pageNumberEncodedParam:
      in: query
      name: page[number]
      description: The Base64-encoded page number of records to return.
      required: false
      schema:
        type: string
        example: Mg==
  responses:
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
    NoContent:
      description: No content.
    ResourceTypeMismatch:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: resource_type_mismatch
              title: Resource type mismatch
              detail: 'The requested data type, a-bad-type, is incompatible with the endpoint.

                '
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
