openapi: 3.2.0
info:
  title: HighBond API Reference Results files API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Results files
  description: 'A results file is a supporting document or concluding memo that relates to a project. Results files typically contain information associated

    with the reporting phase of a project.


    > **Note —**

    Only results files in projects that have an `"active"` state can be accessed using the API.


    Learn more about results files.'
paths:
  /orgs/{org_id}/projects/{project_id}/results_files:
    get:
      tags:
      - Results files
      operationId: getResultsFiles
      summary: Get results files
      description: Get results files that belong to a project.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/projectIdParam'
      - $ref: '#/components/parameters/resultsFileSparseFieldsetParams'
      - $ref: '#/components/parameters/pageSizeParam'
      - $ref: '#/components/parameters/pageNumberEncodedParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetResultsFilesResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - Results files
      operationId: createResultsFile
      summary: Create a results file
      description: 'Create a new results file in an existing project.


        Limitations:

        * There can be a maximum of 1000 results files per project.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/projectIdParam'
      - $ref: '#/components/parameters/resultsFileSparseFieldsetParams'
      requestBody:
        description: The data required to create a results file.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateResultsFileRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetResultsFileResponse'
        '400':
          $ref: '#/components/responses/MissingProjectId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/name
                  code: invalid_resource
                  detail: can't be blank
  /orgs/{org_id}/results_files/{id}:
    get:
      tags:
      - Results files
      operationId: getResultsFile
      summary: Get a results file
      description: 'Get information about a results file.


        Limitation:

        Existing Citation Mode highlights and links are not displayed in the `description` field.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/resultsFileSparseFieldsetParams'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetResultsFileResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
      - Results files
      operationId: updateResultsFile
      summary: Update a results file
      description: 'Make changes to a results file, like renaming it or updating its description.


        Limitations:

        * You cannot update the results file if it is signed off.

        * Existing Citation Mode highlights and links are not displayed in the `description` field.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/resultsFileSparseFieldsetParams'
      requestBody:
        description: The data required to update a results file.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateResultsFileRequest'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetResultsFileResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/name
                  code: invalid_resource
                  detail: can't be blank
    delete:
      tags:
      - Results files
      operationId: deleteResultsFile
      summary: Delete a results file
      description: 'Delete a results file from a project.


        > **Caution —**

        Deleting a results file is permanent. Once deleted, you cannot access or restore the results file.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/base
                  code: invalid_resource
                  title: Invalid resource
                  detail: This results file cannot be deleted because the preparer has already signed off.
components:
  parameters:
    resultsFileSparseFieldsetParams:
      in: query
      name: fields[results_files]
      description: Requesting the API to return only the specified fields. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: name,reference_id,description,position,created_at,updated_at,custom_attributes,project,planned_start_date,actual_start_date,planned_end_date,actual_end_date,planned_milestone_date,actual_milestone_date
    projectIdParam:
      in: path
      name: project_id
      description: The ID of the project.
      required: true
      schema:
        type: integer
        example: 1
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    pageSizeParam:
      in: query
      name: page[size]
      description: The number of items returned per page. Default is 50. Maximum is 100.
      required: false
      schema:
        type: string
        example: 25
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    pageNumberEncodedParam:
      in: query
      name: page[number]
      description: The Base64-encoded page number of records to return.
      required: false
      schema:
        type: string
        example: Mg==
  responses:
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    MissingProjectId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, project_id, is missing.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
    NoContent:
      description: No content.
  schemas:
    GetResultsFileResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: 1
            type:
              type: string
              description: The classification of the object (`"results_files"`).
              example: results_files
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                name:
                  type: string
                  description: The name of the results file.
                  maxLength: 255
                  example: Results File Name
                reference_id:
                  type: string
                  description: The results id, reference number, or code for the results file.
                  maxLength: 8
                  example: BPWS1
                description:
                  type: string
                  description: A detailed description of the results file.
                  maxLength: 524288
                  example: <h1>Results file heading</h1><p>Results file description.</p>
                position:
                  type: integer
                  format: int64
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
                custom_attributes:
                  type: array
                  description: An array of custom attributes defined on the project type used by the project this results file is from. <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-project-types" target="_blank">Learn more about project types</a>. Make a PATCH request to modify the value of a custom attribute.
                  items:
                    type: object
                    description: A user defined custom attribute value.
                    properties:
                      id:
                        type: string
                        description: The ID of this custom attribute. Optional if term is included.
                        example: '42'
                      term:
                        type: string
                        description: The user defined term used to identify this custom attribute. Optional if id is included.
                        example: Custom Results Attribute
                      value:
                        type: array
                        description: The value or values (for multiselect) for this custom attribute.
                        example:
                        - Custom Select Option Text
                        items:
                          type: string
                created_at:
                  type: string
                  description: The timestamp identifying when the results file was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the results file was updated.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                planned_start_date:
                  type:
                  - string
                  - 'null'
                  description: Planned start date
                  example: '2019-02-09'
                  format: date
                planned_end_date:
                  type:
                  - string
                  - 'null'
                  description: Planned end date.
                  example: '2019-02-10'
                  format: date
                actual_start_date:
                  type:
                  - string
                  - 'null'
                  description: Actual start date.
                  example: '2019-02-09'
                  format: date
                actual_end_date:
                  type:
                  - string
                  - 'null'
                  description: Actual end date.
                  example: '2019-02-10'
                  format: date
                actual_milestone_date:
                  type:
                  - string
                  - 'null'
                  description: Actual milestone date.
                  example: '2019-02-10'
                  format: date
                planned_milestone_date:
                  type:
                  - string
                  - 'null'
                  description: Planned milestone date.
                  example: '2019-02-09'
                  format: date
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - project
              properties:
                project:
                  type: object
                  description: Each results file has an associated project. A project is a management system that allows you to define and compile information for reporting purposes.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the object.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the project.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"projects"`).
                          example: projects
    GetResultsFilesResponse:
      type: object
      required:
      - data
      - links
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: 1
              type:
                type: string
                description: The classification of the object (`"results_files"`).
                example: results_files
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  name:
                    type: string
                    description: The name of the results file.
                    maxLength: 255
                    example: Results File Name
                  reference_id:
                    type: string
                    description: The results id, reference number, or code for the results file.
                    maxLength: 8
                    example: BPWS1
                  description:
                    type: string
                    description: A detailed description of the results file.
                    maxLength: 524288
                    example: <h1>Results file heading</h1><p>Results file description.</p>
                  position:
                    type: integer
                    format: int64
                    description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                      '
                    example: 1
                  custom_attributes:
                    type: array
                    description: An array of custom attributes defined on the project type used by the project this results file is from. <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-project-types" target="_blank">Learn more about project types</a>. Make a PATCH request to modify the value of a custom attribute.
                    items:
                      type: object
                      description: A user defined custom attribute value.
                      properties:
                        id:
                          type: string
                          description: The ID of this custom attribute. Optional if term is included.
                          example: '42'
                        term:
                          type: string
                          description: The user defined term used to identify this custom attribute. Optional if id is included.
                          example: Custom Results Attribute
                        value:
                          type: array
                          description: The value or values (for multiselect) for this custom attribute.
                          example:
                          - Custom Select Option Text
                          items:
                            type: string
                  created_at:
                    type: string
                    description: The timestamp identifying when the results file was created.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  updated_at:
                    type: string
                    description: The timestamp identifying when the results file was updated.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  planned_start_date:
                    type:
                    - string
                    - 'null'
                    description: Planned start date
                    example: '2019-02-09'
                    format: date
                  planned_end_date:
                    type:
                    - string
                    - 'null'
                    description: Planned end date.
                    example: '2019-02-10'
                    format: date
                  actual_start_date:
                    type:
                    - string
                    - 'null'
                    description: Actual start date.
                    example: '2019-02-09'
                    format: date
                  actual_end_date:
                    type:
                    - string
                    - 'null'
                    description: Actual end date.
                    example: '2019-02-10'
                    format: date
                  actual_milestone_date:
                    type:
                    - string
                    - 'null'
                    description: Actual milestone date.
                    example: '2019-02-10'
                    format: date
                  planned_milestone_date:
                    type:
                    - string
                    - 'null'
                    description: Planned milestone date.
                    example: '2019-02-09'
                    format: date
              relationships:
                type: object
                description: The relationships associated with the resource.
                required:
                - project
                properties:
                  project:
                    type: object
                    description: Each results file has an associated project. A project is a management system that allows you to define and compile information for reporting purposes.
                    required:
                    - data
                    properties:
                      data:
                        type: object
                        description: The data associated with the object.
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the project.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"projects"`).
                            example: projects
        links:
          type: object
          required:
          - next
          - prev
          properties:
            next:
              type:
              - string
              - 'null'
              description: Next page url
              example: /api/resource?page[number]=Mg==
            prev:
              type:
              - string
              - 'null'
              description: Previous page url
              example: null
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    CreateResultsFileRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The classification of the object (`"results_files"`).
              example: results_files
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - name
              properties:
                name:
                  type: string
                  description: The name of the results file.
                  maxLength: 255
                  example: Results File Name
                reference_id:
                  type: string
                  description: The results id, reference number, or code for the results file.
                  maxLength: 8
                  example: BPWS1
                description:
                  type: string
                  description: A detailed description of the results file.
                  maxLength: 524288
                  example: <h1>Results file heading</h1><p>Results file description.</p>
                position:
                  type: integer
                  format: int64
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
                custom_attributes:
                  type: array
                  description: An array of custom attributes defined on the project type used by the project this results file is from. <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-project-types" target="_blank">Learn more about project types</a>. Make a PATCH request to modify the value of a custom attribute.
                  items:
                    type: object
                    description: A user defined custom attribute value.
                    properties:
                      id:
                        type: string
                        description: The ID of this custom attribute. Optional if term is included.
                        example: '42'
                      term:
                        type: string
                        description: The user defined term used to identify this custom attribute. Optional if id is included.
                        example: Custom Results Attribute
                      value:
                        type: array
                        description: The value or values (for multiselect) for this custom attribute.
                        example:
                        - Custom Select Option Text
                        items:
                          type: string
    UpdateResultsFileRequest:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: 1
            type:
              type: string
              description: The classification of the object (`"results_files"`).
              example: results_files
            attributes:
              type: object
              description: The attributes associated with the planning file.
              required:
              - name
              properties:
                name:
                  type: string
                  description: The name of the results file.
                  maxLength: 255
                  example: Results File Name
                reference_id:
                  type: string
                  description: The results id, reference number, or code for the results file.
                  maxLength: 8
                  example: BPWS1
                description:
                  type: string
                  description: A detailed description of the results file.
                  maxLength: 524288
                  example: <h1>Results file heading</h1><p>Results file description.</p>
                position:
                  type: integer
                  format: int64
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
                custom_attributes:
                  type: array
                  description: An array of custom attributes defined on the project type used by the project this results file is from. <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-project-types" target="_blank">Learn more about project types</a>. Make a PATCH request to modify the value of a custom attribute.
                  items:
                    type: object
                    description: A user defined custom attribute value.
                    properties:
                      id:
                        type: string
                        description: The ID of this custom attribute. Optional if term is included.
                        example: '42'
                      term:
                        type: string
                        description: The user defined term used to identify this custom attribute. Optional if id is included.
                        example: Custom Results Attribute
                      value:
                        type: array
                        description: The value or values (for multiselect) for this custom attribute.
                        example:
                        - Custom Select Option Text
                        items:
                          type: string
                planned_start_date:
                  type:
                  - string
                  - 'null'
                  description: Planned start date
                  example: '2019-02-09'
                  format: date
                planned_end_date:
                  type:
                  - string
                  - 'null'
                  description: Planned end date.
                  example: '2019-02-10'
                  format: date
                actual_start_date:
                  type:
                  - string
                  - 'null'
                  description: Actual start date.
                  example: '2019-02-09'
                  format: date
                actual_end_date:
                  type:
                  - string
                  - 'null'
                  description: Actual end date.
                  example: '2019-02-10'
                  format: date
                actual_milestone_date:
                  type:
                  - string
                  - 'null'
                  description: Actual milestone date.
                  example: '2019-02-10'
                  format: date
                planned_milestone_date:
                  type:
                  - string
                  - 'null'
                  description: Planned milestone date.
                  example: '2019-02-09'
                  format: date
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
