openapi: 3.2.0
info:
  title: HighBond API Reference To Dos API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: To Dos
  description: 'To-dos are a collaboration tool between teammates and reviewers.


    Learn more about to-dos.'
paths:
  /orgs/{org_id}/projects_todos:
    get:
      tags:
      - To Dos
      operationId: getOrgProjectsTodos
      summary: Get organization's to-dos
      description: 'Get a list of all projects to-dos in an organization.


        > **Note:**

        By default, this endpoint only returns to-dos from active projects. To fetch objects from frameworks, do one of the following:

        > * Specify the project or framework ID using `filter[project.id]`

        > * Specify that you want results from frameworks using `filter[project.state]=framework`'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/orgProjectsTodosFieldsetParams'
      - $ref: '#/components/parameters/orgProjectsTodosProjectIdFilterParams'
      - $ref: '#/components/parameters/orgProjectsTodosProjectStateFilterParams'
      - $ref: '#/components/parameters/orgProjectsTodosTargetIdFilterParams'
      - $ref: '#/components/parameters/orgProjectsTodosTargetTypeFilterParams'
      - $ref: '#/components/parameters/orgProjectsTodosSortParams'
      - $ref: '#/components/parameters/pageSizeParam'
      - $ref: '#/components/parameters/pageNumberEncodedParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetOrgProjectsTodosResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - To Dos
      operationId: createTodo
      summary: Create a to-do
      description: Create a new todo in an existing project.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/projectsTodosSparseFieldsetParams'
      - $ref: '#/components/parameters/projectsTodosIncludeParams'
      requestBody:
        description: The data required to create a todo.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CreateTodoResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/status
                  code: invalid_resource
                  detail: is not included in the list
  /orgs/{org_id}/projects_todos/{id}:
    get:
      tags:
      - To Dos
      operationId: getTodo
      summary: Get to-do
      description: Get single project's to-do.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/projectsTodosSparseFieldsetParams'
      - $ref: '#/components/parameters/projectsTodosIncludeParams'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetUpdateTodoResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    patch:
      tags:
      - To Dos
      operationId: updateTodo
      summary: Update a to-do
      description: Make changes to a todo in project or framework, like updating the todo's description, status, due date or relationships.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      - $ref: '#/components/parameters/projectsTodosSparseFieldsetParams'
      - $ref: '#/components/parameters/projectsTodosIncludeParams'
      requestBody:
        description: The data required to update a todo.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetUpdateTodoResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/description
                  code: invalid_resource
                  detail: can't be blank
                - status: 422
                  source:
                    pointer: /data/attributes/status
                  code: invalid_resource
                  detail: is not included in the list
                - status: 422
                  source:
                    pointer: /data/attributes/target
                  code: invalid_resource
                  detail: The target specified is not valid.
    delete:
      tags:
      - To Dos
      operationId: deleteTodo
      summary: Delete a to-do
      description: Permanently delete a todo.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
  /orgs/{org_id}/projects_todos/{todo_id}/comments:
    get:
      tags:
      - To Dos
      operationId: getTodoComments
      summary: Get to-do comments
      description: Get a list of to-do comments
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/projectIdParam'
      - $ref: '#/components/parameters/todoIdParam'
      - $ref: '#/components/parameters/todoCommentSparseFieldsetParams'
      - $ref: '#/components/parameters/todoCommentIncludeParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetTodoCommentsResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - To Dos
      operationId: createTodoComments
      summary: Create a to-do comment
      description: Create a new to-do comment
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/projectIdParam'
      - $ref: '#/components/parameters/todoIdParam'
      requestBody:
        description: The data required to create a to-do comment.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateTodoCommentRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetTodoCommentResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/text
                  code: invalid_resource
                  detail: can't be blank
components:
  parameters:
    projectIdParam:
      in: path
      name: project_id
      description: The ID of the project.
      required: true
      schema:
        type: integer
        example: 1
    todoCommentIncludeParam:
      in: query
      name: include
      description: Requesting the API to return related resources.
      required: false
      schema:
        type: string
        enum:
        - user
      example: user
    todoIdParam:
      in: path
      name: todo_id
      description: The ID of the to-do.
      required: true
      schema:
        type: integer
        example: 1
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    orgProjectsTodosProjectStateFilterParams:
      in: query
      name: filter[project.state]
      description: Requesting the API to filter results by project state. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: active
    orgProjectsTodosTargetTypeFilterParams:
      in: query
      name: filter[target.type]
      description: Requesting the API to filter results by target type. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: test_plans
    pageSizeParam:
      in: query
      name: page[size]
      description: The number of items returned per page. Default is 50. Maximum is 100.
      required: false
      schema:
        type: string
        example: 25
    projectsTodosSparseFieldsetParams:
      in: query
      name: fields[projects_todos]
      description: Requesting the API to return only the specified fields. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: description,due_date,status,created_at,updated_at,assigned_to,creator,target
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    pageNumberEncodedParam:
      in: query
      name: page[number]
      description: The Base64-encoded page number of records to return.
      required: false
      schema:
        type: string
        example: Mg==
    orgProjectsTodosSortParams:
      in: query
      name: sort
      description: Orders the resulting resources by the given field. Sorts ascending by default, prefix with `-` to sort descending. You can provide multiple sort fields separated by comma.
      required: false
      schema:
        type: string
        enum:
        - status
        - created_at
        default: id
    todoCommentSparseFieldsetParams:
      in: query
      name: fields[comments]
      description: Requesting the API to return only the specified fields. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: text,user
    orgProjectsTodosFieldsetParams:
      in: query
      name: fields[projects_todos]
      description: Requesting the API to return only specific fields. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
      example: description,created_at,updated_at,due_date,status,project,target
    orgProjectsTodosProjectIdFilterParams:
      in: query
      name: filter[project.id]
      description: Requesting the API to filter results by project ID. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: '1'
    orgProjectsTodosTargetIdFilterParams:
      in: query
      name: filter[target.id]
      description: Requesting the API to filter results by target ID. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: '1'
    projectsTodosIncludeParams:
      in: query
      name: include
      description: Requesting the API to return related resources. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: assigned_to,target,creator
  schemas:
    CreateTodoResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"projects_todos"`).
              example: projects_todos
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - description
              - created_at
              - updated_at
              - due_date
              - status
              properties:
                description:
                  type: string
                  description: A detailed description of the todo.
                  maxLength: 524288
                  example: Todo details
                created_at:
                  type: string
                  description: The timestamp identifying when the todo was created.
                  example: '2021-01-18T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the todo was last updated.
                  example: '2021-01-18T13:17:26Z'
                  format: date-time
                due_date:
                  type: string
                  description: Specifies when the todo should be fulfilled by.
                  example: '2021-01-18'
                  format: date
                status:
                  type: string
                  description: Status of the todo. Can have one of the following values - "open", "cleared", "closed".
                  example: open
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - assigned_to
              - creator
              - target
              properties:
                assigned_to:
                  type: object
                  description: Specifies the user to whom the todo is assigned to.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The unique identifier (UID) of the user. For more information on obtaining this value, see <a href="#section/Making-requests">Making requests</a>.
                          example: YhxzalsjfhauYna
                        type:
                          type: string
                          description: The classification of the object (`"users"`).
                          example: users
                creator:
                  type: object
                  description: Specifies the user to who is the todo's creator.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The unique identifier (UID) of the user. For more information on obtaining this value, see <a href="#section/Making-requests">Making requests</a>.
                          example: YhxzalsjfhauYna
                        type:
                          type: string
                          description: The classification of the object (`"users"`).
                          example: users
                target:
                  type: object
                  description: Specifies the resource that the todo is associated with.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the resource.
                          example: '1'
                        type:
                          type: string
                          description: 'The classification of the object.


                            A target can have one of the following types: `"projects"`, `"controls"`, `"control_tests"`,

                            `"control_test_plans"`, `"issues"`, `"narratives"`, `"objectives"`, `"walkthrough_summaries"`,

                            `"project_files"`, `"project_plannings"`, `"project_results"`, `"risks"`, `"risk_control_matrices"`,

                            `"testing_rounds"`, `"walkthroughs"`.

                            '
                          example: objectives
    GetUpdateTodoResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"projects_todos"`).
              example: projects_todos
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - description
              - created_at
              - updated_at
              - due_date
              - status
              properties:
                description:
                  type: string
                  description: A detailed description of the todo.
                  maxLength: 524288
                  example: Todo details
                created_at:
                  type: string
                  description: The timestamp identifying when the todo was created.
                  example: '2021-01-18T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the todo was last updated.
                  example: '2021-01-18T13:17:26Z'
                  format: date-time
                due_date:
                  type: string
                  description: Specifies when the todo should be fulfilled by.
                  example: '2021-01-18'
                  format: date
                status:
                  type: string
                  description: Status of the todo. Can have one of the following values - "open", "cleared", "closed".
                  example: open
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - assigned_to
              - creator
              - target
              properties:
                assigned_to:
                  type: object
                  description: Specifies the user to whom the todo is assigned to.
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The unique identifier (UID) of the user. For more information on obtaining this value, see <a href="#section/Making-requests">Making requests</a>.
                          example: YhxzalsjfhauYna
                        type:
                          type: string
                          description: The classification of the object (`"users"`).
                          example: users
                creator:
                  type: object
                  description: Specifies the user to who is the todo's creator.
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The unique identifier (UID) of the user. For more information on obtaining this value, see <a href="#section/Making-requests">Making requests</a>.
                          example: YhxzalsjfhauYna
                        type:
                          type: string
                          description: The classification of the object (`"users"`).
                          example: users
                target:
                  type: object
                  description: Specifies the resource that the todo is associated with.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the resource.
                          example: '1'
                        type:
                          type: string
                          description: 'The classification of the object.


                            A target can have one of the following types: `"projects"`, `"controls"`, `"control_tests"`,

                            `"control_test_plans"`, `"issues"`, `"narratives"`, `"objectives"`, `"walkthrough_summaries"`,

                            `"project_files"`, `"project_plannings"`, `"project_results"`, `"risks"`, `"risk_control_matrices"`,

                            `"testing_rounds"`, `"walkthroughs"`.

                            '
                          example: objectives
    GetOrgProjectsTodosResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            - relationships
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '1'
              type:
                type: string
                description: The classification of the object (`"projects_todos"`).
                example: projects_todos
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  description:
                    type: string
                    description: A detailed description of the todo.
                    maxLength: 524288
                    example: Todo details
                  created_at:
                    type: string
                    description: The timestamp identifying when the todo was created.
                    example: '2021-01-18T13:17:26Z'
                    format: date-time
                  updated_at:
                    type: string
                    description: The timestamp identifying when the todo was last updated.
                    example: '2021-01-18T13:17:26Z'
                    format: date-time
                  due_date:
                    type: string
                    description: Specifies when the todo should be fulfilled by.
                    example: '2021-01-18'
                    format: date
                  status:
                    type: string
                    description: Status of the todo. Can have one of the following values - "open", "cleared", "closed".
                    example: open
              relationships:
                type: object
                description: The relationships associated with the resource.
                properties:
                  project:
                    type: object
                    description: Specifies the project that the todo is associated with.
                    properties:
                      data:
                        type: object
                        description: The data associated with a project.
                        properties:
                          id:
                            type: string
                            description: The ID of the project.
                            example: '1'
                          type:
                            type: string
                            description: The classification of the object (`"projects"`).
                            example: projects
                  target:
                    type: object
                    description: Specifies the resource that the todo is associated with.
                    required:
                    - data
                    properties:
                      data:
                        type: object
                        description: The data associated with a project.
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: The ID of the resource.
                            example: '1'
                          type:
                            type: string
                            description: 'The classification of the object.


                              A target can have one of the following types: `"projects"`, `"controls"`, `"control_tests"`,

                              `"control_test_plans"`, `"issues"`, `"narratives"`, `"objectives"`, `"walkthrough_summaries"`,

                              `"project_files"`, `"project_plannings"`, `"project_results"`, `"risks"`, `"risk_control_matrices"`,

                              `"testing_rounds"`, `"walkthroughs"`.

                              '
                            example: objectives
        links:
          type: object
          required:
          - next
          - prev
          properties:
            next:
              type:
              - string
              - 'null'
              description: Next page url
              example: /api/resource?page[number]=Mw==
            prev:
              type:
              - string
              - 'null'
              description: Previous page url
              example: null
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    UpdateTodoRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"projects_todos"`).
              example: projects_todos
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                description:
                  type: string
                  description: A detailed description of the todo.
                  maxLength: 524288
                  example: Todo details
                due_date:
                  type: string
                  description: Specifies when the todo should be fulfilled by.
                  example: '2021-01-18'
                  format: date
                status:
                  type: string
                  description: Status of the todo. Can have one of the following values - "open", "cleared", "closed".
                  example: open
            relationships:
              type: object
              description: The relationships associated with the resource.
              properties:
                assigned_to:
                  type: object
                  description: Specifies the user to whom the todo is assigned to.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The unique identifier (UID) of the user. For more information on obtaining this value, see <a href="#section/Making-requests">Making requests</a>.
                          example: YhxzalsjfhauYna
                        type:
                          type: string
                          description: The classification of the object (`"users"`).
                          example: users
                target:
                  type: object
                  description: Specifies the resource that the todo is associated with.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the resource.
                          example: '1'
                        type:
                          type: string
                          description: 'The classification of the object.


                            A target can have one of the following types: `"projects"`, `"controls"`, `"control_tests"`,

                            `"control_test_plans"`, `"issues"`, `"narratives"`, `"objectives"`, `"walkthrough_summaries"`,

                            `"project_files"`, `"project_plannings"`, `"project_results"`, `"risks"`, `"risk_control_matrices"`,

                            `"testing_rounds"`, `"walkthroughs"`.

                            '
                          example: objectives
    CreateTodoRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          - relationships
          properties:
            type:
              type: string
              description: The classification of the object (`"projects_todos"`).
              example: projects_todos
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - description
              properties:
                description:
                  type: string
                  description: A detailed description of the todo.
                  maxLength: 524288
                  example: Todo details
                due_date:
                  type: string
                  description: Specifies when the todo should be fulfilled by.
                  example: '2021-01-18'
                  format: date
                status:
                  type: string
                  description: Status of the todo. Can have one of the following values - "open", "cleared", "closed".
                  example: open
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - assigned_to
              - target
              properties:
                assigned_to:
                  type: object
                  description: Specifies the user to whom the todo is assigned to.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The unique identifier (UID) of the user. For more information on obtaining this value, see <a href="#section/Making-requests">Making requests</a>.
                          example: YhxzalsjfhauYna
                        type:
                          type: string
                          description: The classification of the object (`"users"`).
                          example: users
                target:
                  type: object
                  description: Specifies the resource that the todo is associated with.
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with a project.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the resource.
                          example: '1'
                        type:
                          type: string
                          description: 'The classification of the object.


                            A target can have one of the following types: `"projects"`, `"controls"`, `"control_tests"`,

                            `"control_test_plans"`, `"issues"`, `"narratives"`, `"objectives"`, `"walkthrough_summaries"`,

                            `"project_files"`, `"project_plannings"`, `"project_results"`, `"risks"`, `"risk_control_matrices"`,

                            `"testing_rounds"`, `"walkthroughs"`.

                            '
                          example: objectives
    GetTodoCommentsResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            - relationships
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '1'
              type:
                type: string
                description: The classification of the object (`"comments"`).
                example: comments
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  text:
                    type: string
                    description: Body of commment.
                    example: Sample body
                  created_at:
                    type: string
                    description: The timestamp identifying when the comment was created.
                    example: '2021-01-18T13:17:26Z'
                    format: date-time
              relationships:
                type: object
                description: The relationships associated with the resource.
                properties:
                  user:
                    type: object
                    description: 'Specifies the user responsible for fulfilling the request.

                      A value in this field will override any values provided in the `owner` and `owner_email` attributes or contact reference fields.

                      This field becomes required if the `owner` attribute is not provided.

                      '
                    required:
                    - data
                    properties:
                      data:
                        type: object
                        description: The data associated with the resource.
                        required:
                        - id
                        - type
                        properties:
                          id:
                            type: string
                            description: 'The unique identifier (UID) of the user. For more information on obtaining this value, see

                              <a href="#section/Making-requests">Making requests</a>.

                              '
                            example: 3NQ6XzAUxqJMnAQ7n4KF
                          type:
                            type: string
                            description: The classification of the object (`"users"`).
                            example: users
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    CreateTodoCommentRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The classification of the object (`"comments"`).
              example: comments
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                text:
                  type: string
                  description: Body of commment.
                  example: Sample body
    GetTodoCommentResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"comments"`).
              example: comments
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                text:
                  type: string
                  description: Body of commment.
                  example: Sample body
                created_at:
                  type: string
                  description: The timestamp identifying when the comment was created.
                  example: '2021-01-18T13:17:26Z'
                  format: date-time
            relationships:
              type: object
              description: The relationships associated with the resource.
              properties:
                user:
                  type: object
                  description: 'Specifies the user responsible for fulfilling the request.

                    A value in this field will override any values provided in the `owner` and `owner_email` attributes or contact reference fields.

                    This field becomes required if the `owner` attribute is not provided.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: 'The unique identifier (UID) of the user. For more information on obtaining this value, see

                            <a href="#section/Making-requests">Making requests</a>.

                            '
                          example: 3NQ6XzAUxqJMnAQ7n4KF
                        type:
                          type: string
                          description: The classification of the object (`"users"`).
                          example: users
  responses:
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
    NoContent:
      description: No content.
    ResourceTypeMismatch:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: resource_type_mismatch
              title: Resource type mismatch
              detail: 'The requested data type, a-bad-type, is incompatible with the endpoint.

                '
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
