openapi: 3.2.0
info:
  title: HighBond API Reference Records API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Records
  x-displayName: Table records
  description: Records are rows in a table. Each record can have multiple attributes with values.
paths:
  /orgs/{org_id}/tables/{table_id}/upload:
    post:
      tags:
      - Records
      operationId: uploadRecords
      summary: Upload records data
      description: 'When uploading records, you need to specify column names, data types, and records data.


        Valid data types are `character`, `numeric`, `logical`, `date`, `time`, and `datetime`. For more information, see

        Supported data types.


        > **Caution —**

        Changing a column''s data type can break workflows in HighBond that depend on the affected column, such as visualizations, metrics, triggers, and Results table published to Activity Center.


        Limitations:


        You cannot upload records to Projects tables.


        Each table can contain a maximum of 100,000 records, 500 columns, and 256 characters per field, including blank characters.


        You can upload up to 100 columns at once. For instance, if you need to upload 300 columns, you can do so in batches of 100 columns three times. However, please note that the total number of columns in a table cannot exceed 500.


        You cannot upload more than 100kbs of records nor make multiple requests simultaneously (429 error). To upload more than 100kb of data, split your records into multiple, smaller requests that can be made in sequence.


        If the table contains a primary key field, the values in the field must be unique. This field is used to uniquely identify each record in the table.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/tableIdParam'
      requestBody:
        description: The data required to upload records.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRecordsPayload'
      responses:
        '202':
          description: Accepted.
        '400':
          $ref: '#/components/responses/MissingTableId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/name
                  code: invalid_resource
                  detail: can't be blank
                - status: 422
                  code: unprocessable_entity
                  detail: Maximum number of 100,000 Table Records reached.
  /orgs/{org_id}/tables/{table_id}/records:
    get:
      tags:
      - Records
      operationId: getRecords
      summary: Get records
      description: 'Get all the records in a table.


        > **Note:**

        > * By default, this endpoint returns a maximum of 100,000 records. Records above this limit are truncated.

        > * Use query parameters to filter and get the records you need.

        > * Parameters can be applied to any field in the table with the following data type: Character, Numeric, Date, and Datetime.

        > * You can have a maximum of 2 unique fields in a single query.

        > * You can filter records by a single value or multiple values. For multiple values, add the filter string

        > multiple times with an addition of array indication `[]` to each of filter keys.

        > * The maximum limit of the query string is 6000 characters.

        >

        > Examples:

        > * If you need to get records that are in "New" status:

        > `{protocol}://{server}/v1/orgs/{org_id}/tables/{table_id}/records?filter[metadata.status]=New`

        > * If you need to get records that are in either "New" or "Open" status:

        > `{protocol}://{server}/v1/orgs/{org_id}/tables/{table_id}/records?filter[metadata.status][]=New&filter[metadata.status][]=Open`

        > * If you need to get records that are in either "New" or "Open" status with a publish date of "2022-05-10T00:03:46Z".

        > `{protocol}://{server}/v1/orgs/{org_id}/tables/{table_id}/records?filter[metadata.status][]=New&filter[metadata.status][]=Open&filter[metadata.publish_date]=2022-05-10T00:03:46Z`'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/tableIdParam'
      - $ref: '#/components/parameters/recordStatusFilterParam'
      - $ref: '#/components/parameters/recordAssigneeFilterParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MultiRecordsResponse'
        '400':
          $ref: '#/components/responses/MissingTableId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
  /orgs/{org_id}/tables/{table_id}/records/{id}:
    get:
      tags:
      - Records
      operationId: getRecord
      summary: Get a table record
      description: Get information about a table record.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/tableIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/SingleRecordResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    CreateRecordsPayload:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - columns
          - records
          properties:
            columns:
              type: object
              description: A key value pair. The key represents the column name and the value represents the column data type. See the request sample for details.
              example:
                field_one: character
                field_two: character
            records:
              type: array
              description: A key value pair. The key represents the column name and the value represents the column data. See the request sample for details.
              items:
                type: object
              example:
              - field_one: X
                field_two: '2'
              - field_one: XYZ
                field_two: '676'
        options:
          type: object
          description: The options associated with the resource.
          properties:
            purge:
              type: boolean
              description: Setting to `true` deletes existing records in the table and uploads the new records. Setting to `false` uploads new records and appends them to existing records in the table.
              example: true
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    SingleRecordResponse:
      type: object
      required:
      - columns
      - data
      properties:
        columns:
          type: array
          description: A key value pair. The key represents the column name and the value represents the column data type. See the request sample for details.
          items:
            type: object
          example:
          - field_name: field_one
            display_name: Field one
            data_type: character
          - field_name: field_two
            display_name: Field two
            data_type: character
        data:
          type: object
          description: A key value pair. The key represents the column name and the value represents the column data. See the request sample for details.
          example:
            field_one: X
            field_two: '2'
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    MultiRecordsResponse:
      type: object
      required:
      - columns
      - data
      properties:
        columns:
          type: array
          description: A key value pair. The key represents the column name and the value represents the column data type. See the request sample for details.
          items:
            type: object
          example:
          - field_name: field_one
            display_name: Field one
            data_type: character
          - field_name: field_two
            display_name: Field two
            data_type: character
        data:
          type: array
          description: A key value pair. The key represents the column name and the value represents the column data. See the request sample for details.
          items:
            type: object
          example:
          - field_one: X
            field_two: '2'
          - field_one: XYZ
            field_two: '676'
  parameters:
    recordAssigneeFilterParam:
      in: query
      name: filter[metadata.assignee]
      description: Requesting the API to return records with the specified assignees only. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: Bob%20Marley
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    recordStatusFilterParam:
      in: query
      name: filter[metadata.status][]
      description: Requesting the API to return records with the specified statuses only. To filter the records for multiple values, add the filter string multiple times. For example, if you need to get records that have either "New" or "Open" status, pass the filters as follows `?filter[metadata.status][]=New&filter[metadata.status][]=Open`. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: New
    tableIdParam:
      in: path
      name: table_id
      description: The ID of the table.
      required: true
      schema:
        type: integer
        example: 300
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
    MissingTableId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, table_id, is missing.
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
