openapi: 3.2.0
info:
  title: HighBond API Reference Users API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Users
  description: 'A user represents a member of HighBond. Users can belong to multiple instances.


    Learn more about adding and managing users.'
paths:
  /orgs/{org_id}/users:
    get:
      tags:
      - Users
      operationId: getUsers
      summary: List users in an instance
      description: 'Get a list of users, excluding system and root users, who are part of a particular HighBond instance.


        Additional details: The filters have a priority order and at a time one filter can be applied. The priority is as follows:

        1. filter[user_type]

        2. filter[query]

        3. filter[membership_role]


        When multiple filters are passed, the filter with the highest priority is applied.


        Note: System and root users are special types of users that act on behalf of the HighBond platform, like in automation tasks performed in the Robots app. Filters can be applied to query for them if needed.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/listUsersTypeFilterParam'
      - $ref: '#/components/parameters/listMembershipRoleFilterParam'
      - $ref: '#/components/parameters/listUsersSearchParam'
      - $ref: '#/components/parameters/userPageSizeParam'
      - $ref: '#/components/parameters/userPageNumberParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MultipleUsersResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
      - Users
      operationId: createUser
      summary: Create a new user
      description: Add a user to a HighBond instance.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      requestBody:
        description: The data required to create a user.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
  /orgs/{org_id}/users/{uid}:
    get:
      tags:
      - Users
      operationId: getUser
      summary: Get user information
      description: Get basic information for a single user.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/uidPathParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
      - Users
      operationId: updateUser
      summary: Update user information
      description: Updates basic information for a single user.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/uidPathParam'
      requestBody:
        description: The data required to update a user.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/UpdateUserResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
    delete:
      tags:
      - Users
      operationId: deleteUser
      summary: Remove user from organization
      description: Removes the membership of a user to an organization.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/uidPathParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/DeleteUserResponse'
        '400':
          $ref: '#/components/responses/CannotRemoveOnlyAdminInOrg'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  parameters:
    listMembershipRoleFilterParam:
      in: query
      name: filter[membership_role]
      description: Requesting the API to filter Users by their type of membership role in the organization. Can only be one of the following types `"admin"`, and `"member"`
      required: false
      schema:
        type: string
        example: admin
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    userPageSizeParam:
      in: query
      name: page[size]
      description: The number of items returned per page. Default and maximum is 8000 to support backwards compatibility. Recommended best practice is to use 20-50 for user interface usage, and 100-500 for API usage.
      required: false
      schema:
        type: number
      example: 100
    userPageNumberParam:
      in: query
      name: page[number]
      description: The page number of records to return. Default is 1.
      required: false
      schema:
        type: number
      example: 1
    uidPathParam:
      name: uid
      description: The UID of the user.
      schema:
        type: string
        example: yvqdNCtv8TeM47WQtzau
      in: path
      required: true
    listUsersSearchParam:
      in: query
      name: filter[query]
      description: Requesting the API to return only Users matching their name or email if it contains the search query string. Case-insensitive.
      required: false
      schema:
        type: string
        example: diligent.com
    listUsersTypeFilterParam:
      in: query
      name: filter[user_type]
      description: Requesting the API to filter Users by their type. Can only be one of the following types `"user"`, `"system"`, and `"root"`
      required: false
      schema:
        type: string
        example: user
  responses:
    CannotRemoveOnlyAdminInOrg:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: cannot_remove_only_admin_in_org
              title: Cannot remove only Admin in Org
              detail: You need at least one Administrator in the Org.
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    TooManyRequests:
      description: Too many requests.
    UnprocessableEntity:
      description: Unprocessable entity.
  schemas:
    CreateUserRequest:
      type: object
      description: The parameters required to create a new user.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the new user.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The classification of the object (`"users"`) for API schema serialization purposes.
              example: users
            attributes:
              type: object
              description: The attributes associated with the new user.
              required:
              - name
              - first_name
              - last_name
              - email
              properties:
                email:
                  type: string
                  description: The user's email address, defined when that user was created.
                  example: john.smith.test@wegalvanize.com
                first_name:
                  type: string
                  description: First name for the user. The character limit is 40.
                  example: John
                last_name:
                  type: string
                  description: Last name for the user. The character limit is 40.
                  example: Smith
                title:
                  type: string
                  description: The user's professional title. The character limit is 255.
                  example: Prof.
                initials:
                  type: string
                  description: The initials of this user's first and last names. The character limit is 255.
                  example: JS
                phone:
                  type: string
                  description: The user's phone number. This can be with or without hyphens.
                  example: 555-555-5555
                phone_extension:
                  type: string
                  description: The user's phone extension.
                  example: '555'
                date_format:
                  type: string
                  description: The date format this user uses when they view timestamped fields in HighBond.
                  example: '%m/%d/%Y'
                timezone:
                  type: string
                  description: The user's timezone.
                  example: UTC
                company:
                  type: string
                  description: "The user's company name. Maximum 255 characters. Whitespace is trimmed. This field is informational only and \nis not linked to any organizations the user belongs to within the platform.\n"
                  example: Diligent
                locale:
                  type: string
                  description: 'The two letter code representing the user''s chosen locale in their HighBond profile.

                    The available locales are `"de"`, `"en"`, `"es"`, `"fr"`, `"pt"`, `"ja"`, and `"zh"`.

                    '
                  example: en
                created_at:
                  type: string
                  description: The date and time when the user was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                current_sign_in_at:
                  type: string
                  description: The date and time when the user last signed in.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                preferred_community_org_id:
                  type: integer
                  format: int64
                  description: The id of the preferred HighBond instance for the user to access community.
                  example: 12345
                membership:
                  type: object
                  properties:
                    role:
                      type: string
                      description: The role of the user in the organization. Can only be one of the following types `"admin"`, and `"member"`. Default is `"member"`.
                      example: member
    MultipleUsersResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          description: An array of the users within this HighBond instance.
          items:
            type: object
            required:
            - id
            - type
            - attributes
            properties:
              id:
                type: string
                description: The user ID for the user, used across all HighBond instances.
                example: P2tuGWyTWxCAQgTd1XKx
              type:
                type: string
                description: The classification of the object (`"users"`) for API schema serialization purposes.
                example: users
              attributes:
                type: object
                properties:
                  email:
                    type: string
                    description: The user's email address, defined when that user was created.
                    example: john.smith.test@wegalvanize.com
                  first_name:
                    type: string
                    description: First name for the user. The character limit is 40.
                    example: John
                  last_name:
                    type: string
                    description: Last name for the user. The character limit is 40.
                    example: Smith
                  title:
                    type: string
                    description: The user's professional title. The character limit is 255.
                    example: Prof.
                  initials:
                    type: string
                    description: The initials of this user's first and last names. The character limit is 255.
                    example: JS
                  phone:
                    type: string
                    description: The user's phone number. This can be with or without hyphens.
                    example: 555-555-5555
                  phone_extension:
                    type: string
                    description: The user's phone extension.
                    example: '555'
                  date_format:
                    type: string
                    description: The date format this user uses when they view timestamped fields in HighBond.
                    example: '%m/%d/%Y'
                  timezone:
                    type: string
                    description: The user's timezone.
                    example: UTC
                  company:
                    type: string
                    description: "The user's company name. Maximum 255 characters. Whitespace is trimmed. This field is informational only and \nis not linked to any organizations the user belongs to within the platform.\n"
                    example: Diligent
                  locale:
                    type: string
                    description: 'The two letter code representing the user''s chosen locale in their HighBond profile.

                      The available locales are `"de"`, `"en"`, `"es"`, `"fr"`, `"pt"`, `"ja"`, and `"zh"`.

                      '
                    example: en
                  created_at:
                    type: string
                    description: The date and time when the user was created.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  current_sign_in_at:
                    type: string
                    description: The date and time when the user last signed in.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  name:
                    type: string
                    description: The user's full name. This value is system generated, based on `"first_name"` and `"last_name"`.
                    example: John Smith
                  preferred_community_org:
                    type: string
                    description: The name of the user's preferred community instance.
                    example: Organization A
                  preferred_community_org_id:
                    type: integer
                    format: int64
                    description: The id of the preferred HighBond instance for the user to access community.
                    example: 12345
                  user_type:
                    type: string
                    description: The type of user in the HighBond instance, one of `"user"`, `"system"` or `"root"`.
                    example: user
                  enabled:
                    type: boolean
                    description: Shows if the user is enabled or not in the platform.
                    example: true
                  subscription:
                    type: string
                    description: 'The type of user subscription in this HighBond instance. This field will be returned to provide information, currently it cannot be updated via APIs.

                      Available codes are: `"grc_full"` for _Professional_, `"grc_lite"` for _Contributor_, `"grc_intermediate"` for _Oversight_,

                      `"grc_results_cloud_admin"` for _Results Lite Professional_, `"grc_results_cloud_user"` for _Results Lite Contributor_, and `null` for _None_.

                      '
                    example: grc_full
                  is_system_admin:
                    type: boolean
                    description: Returns true when the user is a System Admin in this HighBond instance.
                    example: false
                  is_external:
                    type: boolean
                    description: Returns true when the user is managed externally and synced into this HighBond instance.
                    example: false
                  extended_attributes:
                    type: object
                    description: Set of key-value pairs containing up to 13 attributes defined externally in the user sync service.
                    example:
                      key1: one
                      key2: two
                      key3: three
                      key4: four
                      key5: five
                      key6: six
                      key7: seven
                      key8: eight
                      key9: nine
                      key10: ten
                      key11: eleven
                      key12: twelve
                      key13: thirteen
        links:
          type: object
          description: Links to the first, last, next, and previous pages.
          required:
          - next
          - prev
          - first
          - last
          - self
          properties:
            next:
              type: string
              description: Next page url
              example: /orgs/:org_id/users?page[number]=2&page[size]=10
            prev:
              type: string
              description: Previous page url
              example: /orgs/:org_id/users?page[number]=1&page[size]=10
            first:
              type: string
              description: First page url
              example: /orgs/:org_id/users?page[number]=1&page[size]=10
            last:
              type: string
              description: Last page url
              example: /orgs/:org_id/users?page[number]=1&page[size]=10
            self:
              type: string
              description: Current page url
              example: /orgs/:org_id/users?page[number]=1&page[size]=10
        meta:
          type: object
          description: Metadata about the users pagination.
          required:
          - total_pages
          - total_count
          properties:
            total_pages:
              type: integer
              format: int64
              description: Total number of pages
              example: 1
            total_count:
              type: integer
              format: int64
              description: Total number of users
              example: 1
    DeleteUserResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The user ID for the user, used across all HighBond instances.
              example: P2tuGWyTWxCAQgTd1XKx
            type:
              type: string
              description: The classification of the object (`"users"`) for API schema serialization purposes.
              example: users
            attributes:
              type: object
              properties:
                uid:
                  type: string
                  description: The user ID for the user, used across all HighBond instances.
                  example: P2tuGWyTWxCAQgTd1XKx
                is_root_user:
                  type: boolean
                  description: Returns true when the user is the root user in this HighBond instance.
                  example: false
                email:
                  type: string
                  description: The user's email address, defined when that user was created.
                  example: john.smith.test@wegalvanize.com
                first_name:
                  type: string
                  description: First name for the user. The character limit is 40.
                  example: John
                last_name:
                  type: string
                  description: Last name for the user. The character limit is 40.
                  example: Smith
                title:
                  type: string
                  description: The user's professional title. The character limit is 255.
                  example: Prof.
                initials:
                  type: string
                  description: The initials of this user's first and last names. The character limit is 255.
                  example: JS
                phone:
                  type: string
                  description: The user's phone number. This can be with or without hyphens.
                  example: 555-555-5555
                phone_extension:
                  type: string
                  description: The user's phone extension.
                  example: '555'
                date_format:
                  type: string
                  description: The date format this user uses when they view timestamped fields in HighBond.
                  example: '%m/%d/%Y'
                timezone:
                  type: string
                  description: The user's timezone.
                  example: UTC
                company:
                  type: string
                  description: "The user's company name. Maximum 255 characters. Whitespace is trimmed. This field is informational only and \nis not linked to any organizations the user belongs to within the platform.\n"
                  example: Diligent
                locale:
                  type: string
                  description: 'The two letter code representing the user''s chosen locale in their HighBond profile.

                    The available locales are `"de"`, `"en"`, `"es"`, `"fr"`, `"pt"`, `"ja"`, and `"zh"`.

                    '
                  example: en
                created_at:
                  type: string
                  description: The date and time when the user was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                current_sign_in_at:
                  type: string
                  description: The date and time when the user last signed in.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                name:
                  type: string
                  description: The user's full name. This value is system generated, based on `"first_name"` and `"last_name"`.
                  example: John Smith
                preferred_community_org:
                  type: string
                  description: The name of the user's preferred community instance.
                  example: Organization A
                preferred_community_org_id:
                  type: integer
                  format: int64
                  description: The id of the preferred HighBond instance for the user to access community.
                  example: 12345
                user_type:
                  type: string
                  description: The type of user in the HighBond instance, one of `"user"`, `"system"` or `"root"`.
                  example: user
                enabled:
                  type: boolean
                  description: Shows if the user is enabled or not in the platform.
                  example: true
                subscription:
                  type: string
                  description: 'The type of user subscription in this HighBond instance. This field will be returned to provide information, currently it cannot be updated via APIs.

                    Available codes are: `"grc_full"` for _Professional_, `"grc_lite"` for _Contributor_, `"grc_intermediate"` for _Oversight_,

                    `"grc_results_cloud_admin"` for _Results Lite Professional_, `"grc_results_cloud_user"` for _Results Lite Contributor_, and `null` for _None_.

                    '
                  example: grc_full
                is_system_admin:
                  type: boolean
                  description: Returns true when the user is a System Admin in this HighBond instance.
                  example: false
                is_external:
                  type: boolean
                  description: Returns true when the user is managed externally and synced into this HighBond instance.
                  example: false
                extended_attributes:
                  type: object
                  description: Set of key-value pairs containing up to 13 attributes defined externally in the user sync service.
                  example:
                    key1: one
                    key2: two
                    key3: three
                    key4: four
                    key5: five
                    key6: six
                    key7: seven
                    key8: eight
                    key9: nine
                    key10: ten
                    key11: eleven
                    key12: twelve
                    key13: thirteen
    UpdateUserResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The user ID for the user, used across all HighBond instances.
              example: P2tuGWyTWxCAQgTd1XKx
            type:
              type: string
              description: The classification of the object (`"users"`) for API schema serialization purposes.
              example: users
            attributes:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email address, defined when that user was created.
                  example: john.smith.test@wegalvanize.com
                first_name:
                  type: string
                  description: First name for the user. The character limit is 40.
                  example: John
                last_name:
                  type: string
                  description: Last name for the user. The character limit is 40.
                  example: Smith
                title:
                  type: string
                  description: The user's professional title. The character limit is 255.
                  example: Prof.
                initials:
                  type: string
                  description: The initials of this user's first and last names. The character limit is 255.
                  example: JS
                phone:
                  type: string
                  description: The user's phone number. This can be with or without hyphens.
                  example: 555-555-5555
                phone_extension:
                  type: string
                  description: The user's phone extension.
                  example: '555'
                date_format:
                  type: string
                  description: The date format this user uses when they view timestamped fields in HighBond.
                  example: '%m/%d/%Y'
                timezone:
                  type: string
                  description: The user's timezone.
                  example: UTC
                company:
                  type: string
                  description: "The user's company name. Maximum 255 characters. Whitespace is trimmed. This field is informational only and \nis not linked to any organizations the user belongs to within the platform.\n"
                  example: Diligent
                locale:
                  type: string
                  description: 'The two letter code representing the user''s chosen locale in their HighBond profile.

                    The available locales are `"de"`, `"en"`, `"es"`, `"fr"`, `"pt"`, `"ja"`, and `"zh"`.

                    '
                  example: en
                created_at:
                  type: string
                  description: The date and time when the user was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                current_sign_in_at:
                  type: string
                  description: The date and time when the user last signed in.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                name:
                  type: string
                  description: The user's full name. This value is system generated, based on `"first_name"` and `"last_name"`.
                  example: John Smith
                preferred_community_org:
                  type: string
                  description: The name of the user's preferred community instance.
                  example: Organization A
                preferred_community_org_id:
                  type: integer
                  format: int64
                  description: The id of the preferred HighBond instance for the user to access community.
                  example: 12345
                user_type:
                  type: string
                  description: The type of user in the HighBond instance, one of `"user"`, `"system"` or `"root"`.
                  example: user
                enabled:
                  type: boolean
                  description: Shows if the user is enabled or not in the platform.
                  example: true
                subscription:
                  type: string
                  description: 'The type of user subscription in this HighBond instance. This field will be returned to provide information, currently it cannot be updated via APIs.

                    Available codes are: `"grc_full"` for _Professional_, `"grc_lite"` for _Contributor_, `"grc_intermediate"` for _Oversight_,

                    `"grc_results_cloud_admin"` for _Results Lite Professional_, `"grc_results_cloud_user"` for _Results Lite Contributor_, and `null` for _None_.

                    '
                  example: grc_full
                is_system_admin:
                  type: boolean
                  description: Returns true when the user is a System Admin in this HighBond instance.
                  example: false
                is_external:
                  type: boolean
                  description: Returns true when the user is managed externally and synced into this HighBond instance.
                  example: false
                extended_attributes:
                  type: object
                  description: Set of key-value pairs containing up to 13 attributes defined externally in the user sync service.
                  example:
                    key1: one
                    key2: two
                    key3: three
                    key4: four
                    key5: five
                    key6: six
                    key7: seven
                    key8: eight
                    key9: nine
                    key10: ten
                    key11: eleven
                    key12: twelve
                    key13: thirteen
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    GetUserResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The user ID for the user, used across all HighBond instances.
              example: P2tuGWyTWxCAQgTd1XKx
            type:
              type: string
              description: The classification of the object (`"users"`) for API schema serialization purposes.
              example: users
            attributes:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email address, defined when that user was created.
                  example: john.smith.test@wegalvanize.com
                first_name:
                  type: string
                  description: First name for the user. The character limit is 40.
                  example: John
                last_name:
                  type: string
                  description: Last name for the user. The character limit is 40.
                  example: Smith
                title:
                  type: string
                  description: The user's professional title. The character limit is 255.
                  example: Prof.
                initials:
                  type: string
                  description: The initials of this user's first and last names. The character limit is 255.
                  example: JS
                phone:
                  type: string
                  description: The user's phone number. This can be with or without hyphens.
                  example: 555-555-5555
                phone_extension:
                  type: string
                  description: The user's phone extension.
                  example: '555'
                date_format:
                  type: string
                  description: The date format this user uses when they view timestamped fields in HighBond.
                  example: '%m/%d/%Y'
                timezone:
                  type: string
                  description: The user's timezone.
                  example: UTC
                company:
                  type: string
                  description: "The user's company name. Maximum 255 characters. Whitespace is trimmed. This field is informational only and \nis not linked to any organizations the user belongs to within the platform.\n"
                  example: Diligent
                locale:
                  type: string
                  description: 'The two letter code representing the user''s chosen locale in their HighBond profile.

                    The available locales are `"de"`, `"en"`, `"es"`, `"fr"`, `"pt"`, `"ja"`, and `"zh"`.

                    '
                  example: en
                created_at:
                  type: string
                  description: The date and time when the user was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                current_sign_in_at:
                  type: string
                  description: The date and time when the user last signed in.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                name:
                  type: string
                  description: The user's full name. This value is system generated, based on `"first_name"` and `"last_name"`.
                  example: John Smith
                preferred_community_org:
                  type: string
                  description: The name of the user's preferred community instance.
                  example: Organization A
                preferred_community_org_id:
                  type: integer
                  format: int64
                  description: The id of the preferred HighBond instance for the user to access community.
                  example: 12345
                user_type:
                  type: string
                  description: The type of user in the HighBond instance, one of `"user"`, `"system"` or `"root"`.
                  example: user
                enabled:
                  type: boolean
                  description: Shows if the user is enabled or not in the platform.
                  example: true
                subscription:
                  type: string
                  description: 'The type of user subscription in this HighBond instance. This field will be returned to provide information, currently it cannot be updated via APIs.

                    Available codes are: `"grc_full"` for _Professional_, `"grc_lite"` for _Contributor_, `"grc_intermediate"` for _Oversight_,

                    `"grc_results_cloud_admin"` for _Results Lite Professional_, `"grc_results_cloud_user"` for _Results Lite Contributor_, and `null` for _None_.

                    '
                  example: grc_full
                is_system_admin:
                  type: boolean
                  description: Returns true when the user is a System Admin in this HighBond instance.
                  example: false
                is_external:
                  type: boolean
                  description: Returns true when the user is managed externally and synced into this HighBond instance.
                  example: false
                extended_attributes:
                  type: object
                  description: Set of key-value pairs containing up to 13 attributes defined externally in the user sync service.
                  example:
                    key1: one
                    key2: two
                    key3: three
                    key4: four
                    key5: five
                    key6: six
                    key7: seven
                    key8: eight
                    key9: nine
                    key10: ten
                    key11: eleven
                    key12: twelve
                    key13: thirteen
    CreateUserResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The user ID for the user, used across all HighBond instances.
              example: P2tuGWyTWxCAQgTd1XKx
            type:
              type: string
              description: The classification of the object (`"users"`) for API schema serialization purposes.
              example: users
            attributes:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email address, defined when that user was created.
                  example: john.smith.test@wegalvanize.com
                first_name:
                  type: string
                  description: First name for the user. The character limit is 40.
                  example: John
                last_name:
                  type: string
                  description: Last name for the user. The character limit is 40.
                  example: Smith
                title:
                  type: string
                  description: The user's professional title. The character limit is 255.
                  example: Prof.
                initials:
                  type: string
                  description: The initials of this user's first and last names. The character limit is 255.
                  example: JS
                phone:
                  type: string
                  description: The user's phone number. This can be with or without hyphens.
                  example: 555-555-5555
                phone_extension:
                  type: string
                  description: The user's phone extension.
                  example: '555'
                date_format:
                  type: string
                  description: The date format this user uses when they view timestamped fields in HighBond.
                  example: '%m/%d/%Y'
                timezone:
                  type: string
                  description: The user's timezone.
                  example: UTC
                company:
                  type: string
                  description: "The user's company name. Maximum 255 characters. Whitespace is trimmed. This field is informational only and \nis not linked to any organizations the user belongs to within the platform.\n"
                  example: Diligent
                locale:
                  type: string
                  description: 'The two letter code representing the user''s chosen locale in their HighBond profile.

                    The available locales are `"de"`, `"en"`, `"es"`, `"fr"`, `"pt"`, `"ja"`, and `"zh"`.

                    '
                  example: en
                created_at:
                  type: string
                  description: The date and time when the user was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                current_sign_in_at:
                  type: string
                  description: The date and time when the user last signed in.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                name:
                  type: string
                  description: The user's full name. This value is system generated, based on `"first_name"` and `"last_name"`.
                  example: John Smith
                preferred_community_org:
                  type: string
                  description: The name of the user's preferred community instance.
                  example: Organization A
                preferred_community_org_id:
                  type: integer
                  format: int64
                  description: The id of the preferred HighBond instance for the user to access community.
                  example: 12345
                user_type:
                  type: string
                  description: The type of user in the HighBond instance, one of `"user"`, `"system"` or `"root"`.
                  example: user
                enabled:
                  type: boolean
                  description: Shows if the user is enabled or not in the platform.
                  example: true
                subscription:
                  type: string
                  description: 'The type of user subscription in this HighBond instance. This field will be returned to provide information, currently it cannot be updated via APIs.

                    Available codes are: `"grc_full"` for _Professional_, `"grc_lite"` for _Contributor_, `"grc_intermediate"` for _Oversight_,

                    `"grc_results_cloud_admin"` for _Results Lite Professional_, `"grc_results_cloud_user"` for _Results Lite Contributor_, and `null` for _None_.

                    '
                  example: grc_full
                is_system_admin:
                  type: boolean
                  description: Returns true when the user is a System Admin in this HighBond instance.
                  example: false
                is_external:
                  type: boolean
                  description: Returns true when the user is managed externally and synced into this HighBond instance.
                  example: false
                extended_attributes:
                  type: object
                  description: Set of key-value pairs containing up to 13 attributes defined externally in the user sync service.
                  example:
                    key1: one
                    key2: two
                    key3: three
                    key4: four
                    key5: five
                    key6: six
                    key7: seven
                    key8: eight
                    key9: nine
                    key10: ten
                    key11: eleven
                    key12: twelve
                    key13: thirteen
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    UpdateUserRequest:
      type: object
      description: The parameters required to update a user.
      required:
      - data
      properties:
        data:
          type: object
          description: The data to update.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The classification of the object (`"users"`) for API schema serialization purposes.
              example: users
            attributes:
              type: object
              description: The attributes associated with the user.
              required:
              - name
              properties:
                email:
                  type: string
                  description: The user's email address, defined when that user was created.
                  example: john.smith.test@wegalvanize.com
                first_name:
                  type: string
                  description: First name for the user. The character limit is 40.
                  example: John
                last_name:
                  type: string
                  description: Last name for the user. The character limit is 40.
                  example: Smith
                title:
                  type: string
                  description: The user's professional title. The character limit is 255.
                  example: Prof.
                initials:
                  type: string
                  description: The initials of this user's first and last names. The character limit is 255.
                  example: JS
                phone:
                  type: string
                  description: The user's phone number. This can be with or without hyphens.
                  example: 555-555-5555
                phone_extension:
                  type: string
                  description: The user's phone extension.
                  example: '555'
                date_format:
                  type: string
                  description: The date format this user uses when they view timestamped fields in HighBond.
                  example: '%m/%d/%Y'
                timezone:
                  type: string
                  description: The user's timezone.
                  example: UTC
                company:
                  type: string
                  description: "The user's company name. Maximum 255 characters. Whitespace is trimmed. This field is informational only and \nis not linked to any organizations the user belongs to within the platform.\n"
                  example: Diligent
                locale:
                  type: string
                  description: 'The two letter code representing the user''s chosen locale in their HighBond profile.

                    The available locales are `"de"`, `"en"`, `"es"`, `"fr"`, `"pt"`, `"ja"`, and `"zh"`.

                    '
                  example: en
                created_at:
                  type: string
                  description: The date and time when the user was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                current_sign_in_at:
                  type: string
                  description: The date and time when the user last signed in.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                preferred_community_org_id:
                  type: integer
                  format: int64
                  description: The id of the preferred HighBond instance for the user to access community.
                  example: 12345
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
